// Vue/vue-router-sample/src/App.vue
<script setup lang="ts">
import Home from "./components/Home.vue";
import {RouterView} from "vue-router";
</script>

<template>
<h1>Dead Poets Society</h1>
<nav>
  <a class="button" routerLink="" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Home</a>
  <a class="button" routerLink="/login" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Login</a>
  <a class="button" routerLink="/register" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Register</a>
  <a class="button" routerLink="/clubs" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Clubs</a>
  <a class="button" routerLink="/settings" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Settings</a>
  <a class="button" routerLink="/profile" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Profile</a>
</nav>
	<RouterView></RouterView>
</template>

<style scoped></style>

// Angular/angular-router/angular-router-sample/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'angular-router-sample';
}

<h1>Dead Poets Society</h1>
<nav>
  <a class="button" routerLink="" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Home</a>
  <a class="button" routerLink="/login" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Login</a>
  <a class="button" routerLink="/register" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Register</a>
  <a class="button" routerLink="/clubs" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Clubs</a>
  <a class="button" routerLink="/settings" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Settings</a>
  <a class="button" routerLink="/profile" routerLinkActive="activeButton" ariaCurrentWhenActive="page">Profile</a>
</nav>
<router-outlet></router-outlet>
