// React/react-router-sample/src/Home.tsx
import { Link, Outlet } from "react-router";
import { routePaths } from "./router/paths";

export default function Home() {
	return (
		<div>
			<h1>Dead Poets Society</h1>
			<nav
				className="navbar"
				style={{
					paddingBottom: "16px",
				}}
			>
				<Link
					to={{
						pathname: routePaths.home(),
					}}
					className="button"
					aria-current="page"
				>
					Home
				</Link>
				<Link
					to={{
						pathname: routePaths.clubs(),
					}}
					className="button"
					aria-current="page"
				>
					Clubs
				</Link>
				<Link
					to={{
						pathname: routePaths.settings(),
					}}
					className="button"
					aria-current="page"
				>
					Settings
				</Link>
				<Link
					to={{
						pathname: routePaths.profile(),
					}}
					className="button"
					aria-current="page"
				>
					Profile
				</Link>
			</nav>
			<Outlet></Outlet>
		</div>
	);
}

// Vue/vue-router-sample/src/components/Home.vue
<template>
	<h1>Dead Poets Society</h1>
	<nav class="navbar">
		<router-link
			to="Login"
			class="button"
			active-class="activeButton"
			aria-current="page"
			>Login</router-link
		>
		<router-link
			to="Register"
			class="button"
			active-class="activeButton"
			aria-current="page"
			>Register</router-link
		>
		<router-link
			to="Clubs"
			class="button"
			active-class="activeButton"
			aria-current="page"
			>Clubs</router-link
		>
		<router-link
			to="Settings"
			class="button"
			active-class="activeButton"
			aria-current="page"
			>Settings</router-link
		>
		<router-link
			to="Profile"
			class="button"
			active-class="activeButton"
			aria-current="page"
			>Profile</router-link
		>
	</nav>
</template>

<script setup lang="ts">
import { RouterLink } from "vue-router";
</script>

<style scoped>
.button {
	padding-right: 16px;
}
</style>
