// Vue/vue-router-sample/src/components/Books.vue
<template>
	<ul v-if="club">
		<li
			v-for="book in club.books"
			:key="book.id"
		>
			<router-link
				:to="{
					name: 'BookOverview',
					params: {
						clubId: club.id,
						bookId: book.id,
					},
				}"
			>
				<h2>{{ book.title }}</h2>
			</router-link>
		</li>
	</ul>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";
import { useClub } from "../composables/useClub";
import { parseClubId } from "../router/parser";

const route = useRoute();

const clubId = computed(() => parseClubId(route));
const { club } = useClub(clubId); // Fetches the book from the server.
</script>

// React/react-router-sample/src/components/Books.tsx
import { Link, useParams } from "react-router";
import { useClub } from "../hooks/useClub";
import { useMemo } from "react";
import { parseClubId } from "../router/parser";
import { routePaths } from "../router/paths";

export default function Books() {
	const params = useParams();
	const clubId = useMemo(() => parseClubId(params), [params]);
	const { club } = useClub(clubId);

	return club ? (
		<div>
			{club.books.length === 0 ? (
				<div>
					<p>No books available at the moment.</p>
				</div>
			) : (
				<ul>
					{club.books.map((book) => {
						return (
							<li key={book.id}>
								<Link
									to={{
										pathname: routePaths.book(club.id, book.id),
									}}
								>
									<h2>{book.title}</h2>
								</Link>
							</li>
						);
					})}
				</ul>
			)}
		</div>
	) : null;
}
