// Vue/vue-router-sample/src/components/Clubs.vue
<template>
	<div>
		<div v-if="clubs.length === 0">
			<p>No clubs available at the moment.</p>
		</div>

		<div v-else>
			<ul>
				<li
					v-for="club in clubs"
					:key="club.id"
					class="club-item"
				>
					<router-link
						:to="{
							name: 'ClubOverview',
							params: {
								clubId: club.id,
							},
						}"
					>
						<h2>{{ club.name }}</h2>
					</router-link>
				</li>
			</ul>
		</div>
	</div>
</template>

<script setup lang="ts">
import { clubData as clubs } from "@/clubs";
</script>

// React/react-router-sample/src/components/Clubs.tsx
import { Link } from "react-router";
import { clubData as clubs } from "../clubs";
import { routePaths } from "../router/paths";

export default function Clubs() {
	return (
		<div>
			{clubs.length === 0 ? (
				<div>
					<p>No clubs available at the moment.</p>
				</div>
			) : (
				<div>
					<ul>
						{clubs.map((club) => {
							return (
								<li key={club.id}>
									<Link
										to={{
											pathname: routePaths.club(club.id),
										}}
									>
										<h2>{club.name}</h2>
									</Link>
								</li>
							);
						})}
					</ul>
				</div>
			)}
		</div>
	);
}
