// Vue/vue-router-sample/src/components/Settings.vue
<template>
	<div>Settings</div>
	<form
		v-if="settings && settingsSource"
		@submit.prevent="saveSettings"
	>
		<h1>Settings</h1>
		<div class="my-2">
			<label for="mainClub">Main Club:</label>
			<input
				id="mainClub"
				type="text"
				v-model="settings.mainClub"
			/>
		</div>

		<div class="my-2">
			<label for="preferredGenres">Preferred Genres:</label>
			<input
				id="preferredGenres"
				type="text"
				v-model="genreInput"
				@keyup.enter="addGenre"
			/>
			<div
				v-for="(genre, index) in settings.preferredGenres"
				:key="index"
				class="my-2"
			>
				<span>{{ genre }}</span>
				<button
					type="button"
					@click="removeGenre(index)"
				>
					Delete
				</button>
			</div>
		</div>

		<div class="my-2">
			<label>Notifications:</label><br />
			<input
				type="checkbox"
				id="email"
				v-model="settings.notifications.email"
			/>
			<label for="email">Email</label><br />

			<input
				type="checkbox"
				id="push"
				v-model="settings.notifications.push"
			/>
			<label for="push">Push</label><br />

			<input
				type="checkbox"
				id="newsletter"
				v-model="settings.notifications.newsletter"
			/>
			<label for="newsletter">Newsletter</label>
		</div>

		<button type="submit">Save Settings</button>
		<button
			type="button"
			@click="resetSettings"
		>
			Reset Settings
		</button>
	</form>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from "vue";

import type { Settings } from "../types/index.ts";
import { SettingsPersistence } from "../persistence/SettingsPersistence.ts";

const settingsSource = ref<Settings | undefined>();
const settings = ref<Settings | undefined>();
const genreInput = ref<string>("");

onMounted(async () => {
	const response = await SettingsPersistence.getSettings();
	if (response) {
		settingsSource.value = response;
	} else {
		const cleanSettings = await SettingsPersistence.resetSettings();
		settingsSource.value = cleanSettings;
	}
});

watch(settingsSource, (newSource) => {
	if (newSource) {
		settings.value = {
			...newSource,
			preferredGenres: [...newSource.preferredGenres],
			notifications: {
				...newSource.notifications,
			},
		};
	}
});

async function saveSettings() {
	if (settings.value) {
		const response = await SettingsPersistence.putSettings(settings.value);
		settingsSource.value = response;
	}
}

function resetSettings() {
	SettingsPersistence.resetSettings().then((response) => {
		settings.value = response;
	});
}

function addGenre() {
	if (genreInput.value && settings.value) {
		settings.value.preferredGenres.push(genreInput.value);
		genreInput.value = "";
	}
}

function removeGenre(index: number) {
	if (settings.value) {
		settings.value.preferredGenres.splice(index, 1);
	}
}
</script>

<style scoped>
.my-2 {
	margin-top: 0.5rem;
	margin-bottom: 0.5rem;
}
</style>

// React/react-router-sample/src/components/Settings.tsx
import { useEffect, useState } from "react";
import { Settings } from "../types";
import { SettingsPersistence } from "../persistence/SettingsPersistence";

export default function () {
	const [settingsSource, setSettingsSource] = useState<Settings | undefined>();
	const [settings, setSettings] = useState<Settings | undefined>();

	const [genreInput, setGenreInput] = useState<string>("");

	// Fetch settings from the server on component mount
	useEffect(() => {
		SettingsPersistence.getSettings().then((responseData) => {
			if (responseData) {
				setSettingsSource(responseData);
			} else {
				SettingsPersistence.resetSettings().then((responseData) => {
					setSettingsSource(responseData);
				});
			}
		});
	}, []);

	// Whenever the settings are loaded from the server, update the settings draft state
	useEffect(() => {
		if (settingsSource) {
			setSettings({
				...settingsSource,
				notifications: {
					...settingsSource.notifications,
				},
			});
		}
	}, [settingsSource]);

	async function saveSettings() {
		if (settings) {
			const responseData = await SettingsPersistence.putSettings(settings);
			setSettingsSource(responseData);
		}
	}

	return settings && settingsSource ? (
		<form
			onSubmit={(e) => {
				e.preventDefault();
				saveSettings();
			}}
		>
			<h1>Settings</h1>
			<div className="my-2">
				<label htmlFor="mainClub">Main Club:</label>
				<input
					type="text"
					id="mainClub"
					value={settings.mainClub}
					onChange={(e) => {
						const newSettings = {
							...settings,
							mainClub: e.target.value,
						};
						setSettings(newSettings);
					}}
				/>
			</div>
			<div className="my-2">
				<label htmlFor="preferredGenres">Preferred Genres:</label>
				<input
					type="text"
					id="preferredGenres"
					value={genreInput}
					onChange={(e) => {
						if (e.target.value) {
							setGenreInput(e.target.value);
						}
					}}
					onKeyUp={(e) => {
						if (e.key === "Enter" && genreInput) {
							const newSettings = {
								...settings,
								preferredGenres: [...settings.preferredGenres, genreInput],
							};
							setSettings(newSettings);
							setGenreInput("");
						}
					}}
				/>
				{settings.preferredGenres.map((genre, index) => (
					<div
						key={index}
						className="my-2"
					>
						<span>{genre}</span>
						<button
							type="button"
							onClick={() => {
								const newSettings = {
									...settings,
									preferredGenres: settings.preferredGenres.filter((_, i) => i !== index),
								};
								setSettings(newSettings);
							}}
						>
							Delete
						</button>
					</div>
				))}
			</div>
			<div className="my-2">
				<label htmlFor="notifications">Notifications:</label>
				<br />
				<input
					type="checkbox"
					id="email"
					checked={settings?.notifications.email}
					onChange={(e) => {
						if (settings) {
							const newSettings = {
								...settings,
								notifications: {
									...settings.notifications,
									email: e.target.checked,
								},
							};
							setSettings(newSettings);
						}
					}}
				/>
				Email
				<br />
				<input
					type="checkbox"
					id="push"
					checked={settings?.notifications.push}
					onChange={(e) => {
						if (settings) {
							const newSettings = {
								...settings,
								notifications: {
									...settings.notifications,
									push: e.target.checked,
								},
							};
							setSettings(newSettings);
						}
					}}
				/>
				Push
				<br />
				<input
					type="checkbox"
					id="newsletter"
					checked={settings?.notifications.newsletter}
					onChange={(e) => {
						if (settings) {
							const newSettings = {
								...settings,
								notifications: {
									...settings.notifications,
									newsletter: e.target.checked,
								},
							};
							setSettings(newSettings);
						}
					}}
				/>
				Newsletter
			</div>
			<button type="submit">Save Settings</button>
			<button
				type="button"
				onClick={() => {
					SettingsPersistence.resetSettings().then((responseData) => {
						setSettings(responseData);
					});
				}}
			>
				Reset Settings
			</button>
		</form>
	) : null;
}
